Адаптивная сетка для главной страницы
htmlacademy-adaptive/1125131-cat-energy-21 pull request #10
Opened 2021-01-09 11:03 UTC by mihaqlovm

2021-01-11 17:06 UTC, mikhin commented
<img width="1280" alt="Screenshot 2021-01-11 at 20 05 55" src="https://user-images.githubusercontent.com/38258318/104214453-81faae00-5448-11eb-877c-6644a5b2529d.png">

Ошибки в консоли браузера

2021-01-11 17:25 UTC, mikhin requested changes

2021-01-11 17:25 UTC, mikhin commented on source/less/variables.less
> +@mobile-width-only: 767px;
Так и непонятно по коду, зачем такой брейкпоинт нужен, если по умолчанию стили и так для мобильной версии. Расскажешь?)

2021-01-11 17:25 UTC, mikhin commented on source/less/variables.less
> +@desktop-max-width: 1441px;
А такое зачем? Тоже по коду непонятно.

2021-01-11 17:25 UTC, mikhin commented on source/less/style.less
> +@import "legend";
Однословные имена классов — некруто, т.к. непонятно

2021-01-11 17:25 UTC, mikhin commented on source/less/radio.less
> +.radio__input:checked + label::after {
По БЭМ нельзя использовать селекторы тегов

2021-01-11 17:25 UTC, mikhin commented on source/less/variables.less
> +@desktop-max-width: 1441px;
Я имею ввиду, что должно быть достаточно этого брейкпоинта: @desktop-width: 1440px;

2021-01-11 17:25 UTC, mikhin commented on source/less/radio.less
> +.radio__item {
По коду непонятно что это за элемент

2021-01-11 17:25 UTC, mikhin commented on source/less/promo-banner.less
> +  grid-area: button;
promo-banner__content => button

неочевидно

2021-01-11 17:25 UTC, mikhin commented on source/less/promo-banner.less
> +    grid-template-areas: "title" "slogan" "button" "image";
А вроде зоны можно и без кавычек называть?

2021-01-11 17:25 UTC, mikhin commented on source/less/promo-banner.less
> +    grid-template-rows: 180px 74px 50px 1fr;
Непонятно почему смешаны разные единицы измерения

2021-01-11 17:25 UTC, mikhin commented on source/less/promo-banner.less
> +    margin: 0 auto;
А нам такое нужно на этом блоке? Или может лучше примиксовать класс блока-контейнера?

2021-01-11 17:25 UTC, mikhin commented on source/less/promo-banner.less
> +    grid-template-areas: "title image" "slogan image" "button image";
не считывается такая структура:

<img width="179" alt="Screenshot 2021-01-11 at 20 11 07" src="https://user-images.githubusercontent.com/38258318/104214969-2ed52b00-5449-11eb-8807-66b26721d7aa.png">

может просто так и напишем?)

2021-01-11 17:25 UTC, mikhin commented on source/less/page.less
> +  display: grid;
А это точно нужно прям для всех страниц? Это же общий блок для всех страниц

2021-01-11 17:25 UTC, mikhin commented on source/less/page.less
> +  display: grid;
А это точно нужно прям для всех страниц? Это же общий блок для всех страниц

2021-01-11 17:25 UTC, mikhin commented on source/less/page-header.less
> +  &__content {
Давай селектор напишем полностью)

2021-01-11 17:25 UTC, mikhin commented on source/less/legend.less
> +.legend {
Что этот блок делает? По имени непонятно

2021-01-11 17:25 UTC, mikhin commented on source/less/input.less
> +.input {
Это текстовый инпут имеется ввиду?

2021-01-11 17:25 UTC, mikhin commented on source/less/function-work.less
> +      content: counter(number);
мега-лайк

2021-01-11 17:25 UTC, mikhin commented on source/less/example-work.less
> +    font-size: 20px;
Всегда лучше указывать font-size в паре с line-height, т.к. это неразделимые типографические свойства блока, т.е. одно всегда завязано на другое.

2021-01-11 17:25 UTC, mikhin commented on source/less/button.less
> +.button__main {
Непонятно что это за элемент

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +              <source srcset="img/logo-tablet.png" media="(max-width: 1439px)">
Везде используем min-width и нигде не используем max-width, если уж верстаем mobile-first

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +          <svg class="main-nav__toggle" aria-label="Открыть меню" width="24" height="18" viewBox="0 0 24 18" fill="none" xmlns="http://www.w3.org/2000/svg">
А кнопка где?

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +                <span class="main-nav__link" href="/catalog.html">Каталог продукции</span>
Спан не может называться ссылкой. Лучше все ссылки переименовать в `main-nav__item-content` чтобы по БЭМу абстрагироваться от семантики HTML

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +                <span class="main-nav__link" href="/catalog.html">Каталог продукции</span>
И атрибут лишний

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +                <a class="main-nav__link main-nav__link--active">Подбор программы</a>
Кажется тут путаница произошла с семантикой

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +      <section class="promo-banner promo-banner__background">
Тут два ая-яй-яй:
1. Не должны хотеть такое имя класса, а соответственно и такую функцию — `promo-banner__background`
2. Такое бывает нужно очень редко — повесить на одну и ту же ноду и БЭМ-блок и его же элемент, поэтому это не считается стандартной практикой. Давай пока тут такое не будем делать)

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +          <a class="button button__main" href="/form.html">Подобрать программу</a>
Тут два ая-яй-яй:

1. Очень странное и непонятное имя класса — `button__main`
2. Такое бывает нужно очень редко — повесить на одну и ту же ноду и БЭМ-блок и его же элемент, поэтому это не считается стандартной практикой. Давай пока тут такое не будем делать)

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +      <div class="example-work__background">
Не должны хотеть такое имя класса и такую функцию

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +      <div class="example-work__background">
БЭМ-элемент не должен лежать снаружи своего БЭМ-блока

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +            <input class="range example-work__range" type="range" min="1" max="2" step="1" value="1">
Тут чтоб не мучаться можно любую кастомную разметку бахнуть, чтоб не париться с таким инпутом

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +          <h2 class="contact__text">Приглашаем к&nbsp;сотрудничеству диллеров!</h2>
Заголовок называется `text` — странно. Плюс `text` — почти всегда плохое слово в нейминге, т.к. это очень общее слово.

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +        <div class="contact__image"></div>
Div называется image. Почему?)

2021-01-11 17:25 UTC, mikhin commented on source/index.html
> +        <div class="page-footer__image">
Div называется image. Почему?)

2021-01-11 18:46 UTC, mihaqlovm commented on source/less/variables.less
> +@mobile-width-only: 767px;
Остатки от тестового периода — когда только-только знакомился с медиа-запросами. Удалил.

2021-01-11 18:50 UTC, mihaqlovm commented on source/less/style.less
> +@import "legend";
form__fieldset и form__legend решат задачу?

2021-01-11 18:53 UTC, mihaqlovm commented on source/less/radio.less
> +.radio__input:checked + label::after {
Подобное получилось потому что я дал имя классу тега `legend` идентично имени селектора тега.

2021-01-11 18:54 UTC, mihaqlovm commented on source/less/radio.less
> +.radio__item {
form-radio решит задачу?

2021-01-11 18:56 UTC, mihaqlovm commented on source/less/promo-banner.less
> +  grid-area: button;
Просто обозвал grid-area так, а не иначе. А что не так?

2021-01-11 19:01 UTC, mihaqlovm commented on source/less/promo-banner.less
> +    grid-template-areas: "title" "slogan" "button" "image";
Может и можно. Но лучше не буду. С кавычками визуально нагляднее отделять одно название от другого.

2021-01-11 19:07 UTC, mihaqlovm commented on source/less/promo-banner.less
> +    grid-template-rows: 180px 74px 50px 1fr;
Решил попробовать делать отступ между текстовыми блоками гридовскими строками. Не надо так?

2021-01-11 19:09 UTC, mihaqlovm commented on source/less/promo-banner.less
> +    margin: 0 auto;
Скорее да, чем нет. Впереди головняк с картинкой, которая на мобиле есть, на табле — нет, а на десктопе опять есть, но на 50% экрана… Пока что оставим. Но взял на заметку — избавлюсь если не понадобится чуть позже.

2021-01-11 19:13 UTC, mihaqlovm commented on source/less/page.less
> +  display: grid;
К сожалению, не нужно. Хотя жаль. Придётся миксовать новые классы к `section`, чтобы добавить отступы.

2021-01-11 19:20 UTC, mihaqlovm commented on source/less/legend.less
> +.legend {
form-legend?

2021-01-11 19:20 UTC, mihaqlovm commented on source/less/input.less
> +.input {
form-input?

2021-01-11 19:23 UTC, mihaqlovm commented on source/less/button.less
> +.button__main {
button__add-program?

2021-01-11 19:26 UTC, mihaqlovm commented on source/index.html
> +          <svg class="main-nav__toggle" aria-label="Открыть меню" width="24" height="18" viewBox="0 0 24 18" fill="none" xmlns="http://www.w3.org/2000/svg">
Так а я решил JS'ом svg активировать.

2021-01-11 19:29 UTC, mihaqlovm commented on source/index.html
> +                <span class="main-nav__link" href="/catalog.html">Каталог продукции</span>
Хз откуда `span` взялся. Исправил на `a` как и у остальных пунктов меню. Поправил ссылки. Но оставил свой нэйминг.

2021-01-11 19:33 UTC, mihaqlovm commented on source/index.html
> +      <section class="promo-banner promo-banner__background">
1. `promo-banner__image`?
2. Просто обернуть `section` в `div`?

2021-01-11 19:37 UTC, mihaqlovm commented on source/index.html
> +          <a class="button button__main" href="/form.html">Подобрать программу</a>
1. `add-program`?
2. Обернуть `a` в `div class="add-program"`, который лежит в `div class="promo-banner__content"`?

2021-01-11 19:37 UTC, mihaqlovm commented on source/index.html
> +      <div class="example-work__background">
Блин (( А как должны хотеть?

2021-01-11 19:38 UTC, mihaqlovm commented on source/index.html
> +      <div class="example-work__background">
Как же мне обозвать класс с фоном, чтобы он имел отношение к блоку, но оборачивал этот блок? ((

2021-01-11 19:40 UTC, mihaqlovm commented on source/index.html
> +            <input class="range example-work__range" type="range" min="1" max="2" step="1" value="1">
На мобиле думаю надо шаманить с чек-боксом. На планшете/десктопе — оставить range. Но я пока не знаю как мне добраться до нутра полоски и передвигалки…

2021-01-11 19:42 UTC, mihaqlovm commented on source/index.html
> +          <h2 class="contact__text">Приглашаем к&nbsp;сотрудничеству диллеров!</h2>
Меняю на `title` и дело в шляпе.

2021-01-11 19:51 UTC, mihaqlovm commented on source/index.html
> +        <div class="contact__image"></div>
Вынести картинки с картой из CSS в HTML или изменить имя на `contact__map`?

2021-01-12 07:33 UTC, mikhin commented on source/less/style.less
> +@import "legend";
Будет получше, да

2021-01-12 07:33 UTC, mikhin commented on source/less/radio.less
> +.radio__input:checked + label::after {
Я не понял

2021-01-12 07:38 UTC, mikhin commented on source/less/radio.less
> +.radio__item {
скорее radio-field

2021-01-12 07:39 UTC, mikhin commented on source/less/promo-banner.less
> +  grid-area: button;
ну типа разные сущности в классе и в свойстве. Может и в свойстве сделать content?

2021-01-12 07:39 UTC, mikhin commented on source/less/promo-banner.less
> +    grid-template-rows: 180px 74px 50px 1fr;
Не понял. Для отступа есть свойство grid-gap или gap

2021-01-12 07:39 UTC, mikhin commented on source/less/legend.less
> +.legend {
ага

2021-01-12 07:40 UTC, mikhin commented on source/less/input.less
> +.input {
text-input

2021-01-12 07:40 UTC, mikhin commented on source/less/input.less
> +.input {
потому что чекбокс и кнопка это тоже инпут

2021-01-12 07:41 UTC, mikhin commented on source/less/button.less
> +.button__main {
не, там семантика в кнопке кривая. Непонятно почему в независимом БЭМ-блоке КНОПКА, который просто кнопка, простая как пень, закралось внутрь знание из вне про какие-то программы и в таком духе

2021-01-12 07:42 UTC, mikhin commented on source/index.html
> +          <svg class="main-nav__toggle" aria-label="Открыть меню" width="24" height="18" viewBox="0 0 24 18" fill="none" xmlns="http://www.w3.org/2000/svg">
Это понятно, но не оч круто. Мы должны хотеть делать интерфейс интерактивным прежде всего из семантики, а потом уже приправлять js'ом. Поэтому нужна семантика интерактивного элемента

2021-01-12 07:43 UTC, mikhin commented on source/index.html
> +      <section class="promo-banner promo-banner__background">
1. Ну, например да. Или можно прям на сам класс бэм-блока бахнуть нужный фон
2. Не оч понял

2021-01-12 07:44 UTC, mikhin commented on source/index.html
> +      <div class="example-work__background">
Должны хотеть выражать в структуре документа именования и сущности функционально, а не визуально. Сейчас это имя класса про визуальщину, а значит оч хрупкое и не считываемое. Надо понять есть ли в этом какая-либо функция из области разработки интерфейсов, и назвать соответствующе. Если нет, то убрать в CSS.

2021-01-12 07:45 UTC, mikhin commented on source/index.html
> +      <div class="example-work__background">
Поменять местами. Саму ноду с фоном обозвать БЭМ-блоком, а внутренний первый элемент назвать __content например.

2021-01-12 07:46 UTC, mikhin commented on source/index.html
> +            <input class="range example-work__range" type="range" min="1" max="2" step="1" value="1">
Надо сделать условное отображение разных БЭМ-блоков в зависимости от брейкпоинта

2021-01-12 07:46 UTC, mikhin commented on source/index.html
> +        <div class="contact__image"></div>
Да и да)

2021-01-12 10:17 UTC, mihaqlovm commented on source/less/style.less
> +@import "legend";
`fieldset__legend`. `form-fieldset`.

2021-01-12 10:24 UTC, mihaqlovm commented on source/less/radio.less
> +.radio__input:checked + label::after {
`radio__label`!!

`<li class="radio__item">`
`<input class="visually-hidden radio__input" type="radio" name="result" value="weight-loss" id="weight-loss" checked>`
`<label class="radio__label" for="weight-loss">Похудение</label>`
`</li>`

2021-01-12 10:28 UTC, mihaqlovm commented on source/less/promo-banner.less
> +  grid-area: button;
Работаем с `content`, а не с `button`.
`<div class="promo-banner__content">`
`<a class="button button__main" href="/form.html">Подобрать программу</a>`
`</div>`

2021-01-12 10:42 UTC, mihaqlovm commented on source/less/button.less
> +.button__main {
Делаем модификатор, а не элемент.
`button button--size--l`

2021-01-12 10:49 UTC, mihaqlovm commented on source/index.html
> +      <section class="promo-banner promo-banner__background">
Вешаем фон на `promo-banner`.

2021-01-12 10:52 UTC, mihaqlovm commented on source/index.html
> +      <div class="example-work__background">
`div` — это блок. Называем его `example-work` и вешаем на него фон.
`section` — меняем имя класса на `example-work__content`.

Всё это вместо:
`<div class="example-work__background">`
`<section class="example-work container">`

2021-01-12 10:54 UTC, mihaqlovm commented on source/index.html
> +            <input class="range example-work__range" type="range" min="1" max="2" step="1" value="1">
Делаем на `div` и «пимпочки» и «полосочки».

2021-01-15 15:33 UTC, mihaqlovm commented on source/index.html
> +        <div class="contact__image"></div>
Класс-то я поменял. Однако если картинки перенести в html, то они у меня не тянутся при адаптации. А вот через CSS всё хорошо. Пожалуй, оставлю пока так.

2021-01-15 16:18 UTC, mihaqlovm commented on source/index.html
> +            <input class="range example-work__range" type="range" min="1" max="2" step="1" value="1">
Займусь этим в след. ДЗэ. Сейчас только адаптивная сетка для главной страницы.

2021-01-16 10:33 UTC, merged