Разметка главной страницы
htmlacademy-adaptive/1125131-cat-energy-21 pull request #3
Opened 2020-11-13 18:56 UTC by mihaqlovm

---
:mortar_board: [Разметка главной страницы](https://up.htmlacademy.ru/adaptive/21/user/1125131/tasks/2)

:boom: https://htmlacademy-adaptive.github.io/1125131-cat-energy-21/3/

2020-11-14 19:06 UTC, mikhin requested changes

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +      <section class="function">
Однословное название класса оч плохо его описывает. Нужно придумать более подробное название (но не сильно), которое опишет его в том числе в предметной области разработки интерфейсов.

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +              <img src="https://via.placeholder.com/30x32" width="30" height="32" alt="Иконка листика" class="function__image">
Пока непонятно нужны ли эти иконки в разметке

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +          <li class="example__item">
`example__list-item`

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +        <p class="example__text">Борис сбросил 5 кг за 2 месяца, просто заменив свой обычный корм на Cat Energy Slim. Отличный результат без изнуряющих тренировок! При этом он не менял своих привычек
Непонятно что за `__text`

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +            <p class="example__number">5 кг</p>
Маловато текста для абзаца)

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +            <p class="example__number">60 дней</p>
Что такое «число примера» неясно)

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +        <img class="example__image example__image--after" src="https://via.placeholder.com/311x232" width="311" height="232" alt="Активный поджарый кот после диеты">
За альты лайк, подписка)

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +        <fieldset class="example__toggle">
Элементы форм не должны использоваться без формы)

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +        <fieldset class="example__toggle">
Что такое «ручка примера» неясно)

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +          <input class="visually-hidden example__before" type="radio" name="example-before" id="example-before">
Что такое «до примера» неясно)

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +          <input class="visually-hidden example__aftere" type="radio" name="example-aftere" id="example-aftere">
Не факт что это радио-кнопки

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +        <p class="contact__text">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
Непонятно что за  `__text`

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +        <p class="contact__text">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
А тег `address` подойдет?

2020-11-14 19:06 UTC, mikhin commented on source/index.html
> +      <ul class="page-footer__list">
Непонятно что за список

2020-11-24 12:01 UTC, mihaqlovm commented on source/index.html
> +      <a href="" class="page-header__logo">
Как принято: сперва нэйминг по родителю, а потом как отдельный блок или наоборот?
"page-header__logo-image logo-image" или "logo-image page-header__logo-image"?

2020-11-24 12:03 UTC, mihaqlovm commented on source/index.html
> +            <li class="main-nav__item main-nav__item--active"><a>Главная</a></li>
Ты модификатор пишешь через двойной дефис (--) или через одинарное нижнее подчёркивание (_)?

2020-11-24 12:10 UTC, mihaqlovm commented on source/index.html
> +        <button class="button">Подобрать программу</button>
У меня получается, что кнопки везде одинаковые и отличаются только размерами на разных экранах. То есть кнопка на смартфоне на главной странице, в форме и в каталоге одинаковая по всем параметрам. Нормально ли если я назову её button__mobile?

2020-11-24 12:31 UTC, mihaqlovm commented on source/index.html
> +              <img src="https://via.placeholder.com/30x32" width="30" height="32" alt="Иконка листика" class="function__image">
Ок. Когда перейдём к стилизации вынесу в CSS.

2020-11-25 08:40 UTC, merged