Добавляет разметку страницы формы
htmlacademy-adaptive/1125131-cat-energy-21 pull request #4
Opened 2020-11-25 13:07 UTC by mihaqlovm

2020-11-26 07:55 UTC, mikhin requested changes

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +        <a href="#" class="page-header__link">
"ссылка в хедере" — непонятно

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +                        <a class="main-nav__link main-nav__link--active">Главная</a>
👍

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +        <section class="program-request page-main__program-request">
👍

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +                    <input class="program-request__input" type="text" name="name" placeholder="БАРСИК" required
Давай поле сделаем отдельным БЭМ-блоком)

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +                    <label class="program-request__label">
Не оч круто, что здесь инпут вложен в лейбл, а в предыдущих полях нет. код становится менее очевидным

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +                        <input class="program-request__radio" type="radio" name="result" value="weight-gain"> Набор
Давай все инпуты (текстовые поля, радио-кнопки, чекбоксы) сделаем отдельными БЭМ-блоками)

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +                    <input class="program-request__input" type="number" min="1" max="21" step="1" name="weight"
Я не уверен что step нужен. Или нужен? Если да, то зачем?

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +                        Похудение
Текст нужно обернуть в отдельный элемент, если уж так

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +                    <span>
В CSS

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +                    <label for="sugar-substitute">Сахарозаменитель</label>
Тут почему-то лейблы идут после инпута

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +            <span class="program-request__required-field">* — Обязательные поля</span>
Лучше абзац

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +            <p class="contact__address">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
Я не намекаю, а реально не знаю. Address подойдет в таком случае? Можешь рассказать?

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +                alt="Мы на карте">
Alt может быть и поинформативнее

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +                <!--svg vk-->
Не, здесь же ссылка должна быть

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +        <div class="copyright">
Где-то здесь ссылка тоже

2020-11-26 07:55 UTC, mikhin commented on source/form.html
> +                alt="Логотип компании создавшей сайт">
Тут нужна не загадка, а отгадка, лол =)

2020-11-26 10:17 UTC, mihaqlovm commented on source/form.html
> +        <a href="#" class="page-header__link">
page-header__logo-link?

2020-11-26 10:18 UTC, mihaqlovm commented on source/form.html
> +                    <input class="program-request__input" type="text" name="name" placeholder="БАРСИК" required
<fieldset class="fieldset program-request__fieldset">?

2020-11-26 10:22 UTC, mihaqlovm commented on source/form.html
> +                    <label class="program-request__label">
Речь об единообразии?

2020-11-26 10:23 UTC, mihaqlovm commented on source/form.html
> +                        <input class="program-request__radio" type="radio" name="result" value="weight-gain"> Набор
Да)

2020-11-26 10:25 UTC, mihaqlovm commented on source/form.html
> +                    <input class="program-request__input" type="number" min="1" max="21" step="1" name="weight"
На мой взгляд нужен. Например, я с помощью мыши без клавиатуры нащёлкаю нужный вес. При клике на поле появляются стрелки увеличения и уменьшения единиц измерения.

2020-11-26 10:26 UTC, mihaqlovm commented on source/form.html
> +                        Похудение
Причина?

2020-11-26 10:27 UTC, mihaqlovm commented on source/form.html
> +                    <span>
Мм…?

2020-11-26 10:28 UTC, mikhin commented on source/form.html
> +        <a href="#" class="page-header__link">
page-header__logo

2020-11-26 10:28 UTC, mikhin commented on source/form.html
> +        <a href="#" class="page-header__link">
link это знание о внутреннем устройстве, а page-header не должен хотеть знать про внутренее

2020-11-26 10:28 UTC, mihaqlovm commented on source/form.html
> +            <span class="program-request__required-field">* — Обязательные поля</span>
Где грань перехода из спана в абзац? Два и больше слова — абзац?

2020-11-26 10:28 UTC, mikhin commented on source/form.html
> +        <a href="#" class="page-header__link">
плюс ссылка легко может перестать быть ссылкой, а стать кнопкой или спаном, из-за этого придется менять нейминг

2020-11-26 10:28 UTC, mikhin commented on source/form.html
> +                    <input class="program-request__input" type="text" name="name" placeholder="БАРСИК" required
не, я про текстовый инпут именно

2020-11-26 10:29 UTC, mikhin commented on source/form.html
> +                    <label class="program-request__label">
ага

2020-11-26 10:31 UTC, mihaqlovm commented on source/form.html
> +            <p class="contact__address">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
Подойдёт )) Например, потому что поисковые системы обращаются внимание на этот тег и при нужном запросе могут выводить адрес сразу в серпе, без перехода на сайт. Также это может быть полезно для ботов всевозможных онлайн-карт. Для бизнеса важно как можно в больших местах заявлять о себе, чтобы привлекать лиды. Ну или как-то так ))

2020-11-26 10:32 UTC, mihaqlovm commented on source/form.html
> +                <!--svg vk-->
Упс…

2020-11-26 10:32 UTC, mihaqlovm commented on source/form.html
> +        <div class="copyright">
Да, да ((

2020-11-26 10:32 UTC, mihaqlovm commented on source/form.html
> +                alt="Логотип компании создавшей сайт">
Ахаха ))

2020-11-26 10:52 UTC, mikhin commented on source/form.html
> +                    <input class="program-request__input" type="number" min="1" max="21" step="1" name="weight"
А если без степ, нащелкать не получится?

2020-11-26 10:53 UTC, mikhin commented on source/form.html
> +                        Похудение
Интерфейс должен считываться из HTML, плюс текст должен быть как-то размечен. Сейчас по сути лейбл перестал был текстовым элементом для "Похудение2, а стал контейнером для всего, поэтому "Похудение" нужно как-то разметить

2020-11-26 10:53 UTC, mikhin commented on source/form.html
> +                    <span>
Этот декоративный элемент будет в CSS)

2020-11-26 10:54 UTC, mikhin commented on source/form.html
> +            <span class="program-request__required-field">* — Обязательные поля</span>
Не могу сказать точно и объективно, просто пишу то, как чувствую из опыта)

2020-11-26 10:54 UTC, mikhin commented on source/form.html
> +            <span class="program-request__required-field">* — Обязательные поля</span>
Ну и еще абзац = предложение в русском языке.

2020-11-26 14:04 UTC, mihaqlovm commented on source/form.html
> +                    <input class="program-request__input" type="number" min="1" max="21" step="1" name="weight"
Получится. Пожалуй, получается, что step лишний. Маловероятно, что когда-либо кто-либо захочет изменить этот шаг, например, даже на 2. Ок, избавляюсь.

2020-11-26 14:05 UTC, mihaqlovm commented on source/form.html
> +                        Похудение
Ок. Положу в span. Хотя я их почему-то боюсь. Как и br. Лишний раз не трогаю. Пока они не начали сниться обращусь к психоаналитику ))

2020-11-26 14:07 UTC, mihaqlovm commented on source/form.html
> +                    <span>
А, ты про <!--Иконка почтового конверта-->в span. Да, ок.

2020-11-26 18:43 UTC, mikhin approved these changes

2020-11-26 18:43 UTC, mikhin commented on source/form.html
> +                    <label class="label program-request__label" for="name">ИМЯ:*</label>
Не надо писать капсом в разметке)

2020-11-26 18:43 UTC, mikhin commented on source/form.html
> +                    <label class="label program-request__label" for="name">ИМЯ:*</label>
Не, так не пойдет =) У нас же кастомные инпуты и стилизовать мы будем через связку input + label, поэтому инпут и лейбл должны быть единым бэм-блоком)

2020-11-26 18:43 UTC, mikhin commented on source/form.html
> +                    <label class="label program-request__label" for="name">ИМЯ:*</label>
Касается всего, и радио и чекбоксов)

2020-11-26 18:43 UTC, mikhin commented on source/form.html
> +            <p class="contact__address">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
Так, а чего не переделал?)

2020-11-26 18:43 UTC, mikhin commented on source/form.html
> +        <div class="copyright">
Так, и где?)

2020-11-26 18:43 UTC, mikhin commented on source/form.html
> +        <div class="copyright">
А, нашел, да

2020-11-26 18:43 UTC, merged

2020-11-27 07:19 UTC, mihaqlovm commented on source/form.html
> +                    <label class="label program-request__label" for="name">ИМЯ:*</label>
У меня опять какая-то путаница. Я комитил следующий код:

```
<label class="label program-request__label" for="age">Возраст (лет):</label>
<input class="input program-request__input" type="number" min="1" max="43" name="age">
<label class="label program-request__label">Не знаю (нужен ваш совет)</label>
<input class="input-radio program-request__radio" type="radio" name="result" value="i-do-not-know">
<label class="label program-request__label" for="vitamins">Витамины</label>
<input class="input-checkbox program-request__checkbox" type="checkbox" name="vitamins" id="vitamins">
```

А тут вижу старый вариант.