Разметил страницу каталога
htmlacademy-adaptive/1125131-cat-energy-21 pull request #5
Opened 2020-11-25 13:26 UTC by mihaqlovm

2020-11-26 08:15 UTC, mikhin requested changes

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +                     <div class="main-goods-card">
Слабоват нейминг, т.к привязка к месту употребления.

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +                        <img class="promo-banner__image" src="https://via.placeholder.com/140x112" width="140" height="112" alt="Банка с питанием для котов Cat Energy Pro со вкусом курицы массой 500
А где родитель?

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +                            <dl>
Классы нужны)

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +                            <dl>
За семантику большущий лайк 👍

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +                        <button class="button button--mobile">Заказать</button>
Это скорей ссылка

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +                        <button class="button button--mobile">Заказать</button>
Если кнопка, то не хватает type=button, т.к. по умолчанию кнопка type=submit

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +             <p class="main-goods__description">Показать еще 100500 товаров</p>
Это какой-то интерактивный элемент

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +         <section class="additional-goods page-header__additional-goods">
`page-header__additional-goods` ваще неожиданно что это ребенок блока `page-header`

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +                     <div class="additional-goods__card">
ДАвай сделаем отдельным бэм-блоком?

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +                            <dt class="visualy-hidden">Объём или вес продукта</dt>
Круть!

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +                         <dl>
Классы нужны)

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +         <section class="additional-goods page-header__additional-goods">
Опечатка наверное

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +         <section class="gift-banner page-header__gift-banner">
Опечатка по принадлежности к родителю

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +    </main>
Нарушена вложенность

2020-11-26 08:15 UTC, mikhin commented on source/catalog.html
> +    </main>
Плюс этот тег уже закрыт ранее

2020-11-26 08:15 UTC, mikhin commented on source/form.html
> +<!DOCTYPE html>
Этой страницы по идее быть не должно тут =)

Ты создал ветку для каталога из ветки с формой, а должен был создать из мастер-ветки, т.к. это разные фичи и они должны быть в разных ветках.

Это очень важно — фича-ветку каждый раз создавать из мастера

2020-11-26 10:35 UTC, mihaqlovm commented on source/catalog.html
> +                     <div class="main-goods-card">
Абстрагироваться и просто сделать разные виды карточек без привязки к конкретному месту, а в обёртке уже обозначить?

2020-11-26 10:36 UTC, mihaqlovm commented on source/catalog.html
> +                            <dl>
Путаюсь. Классы сделать с привязкой к конкретному блоку или использовать как отдельный блок?

2020-11-26 10:38 UTC, mihaqlovm commented on source/catalog.html
> +                        <button class="button button--mobile">Заказать</button>
В моём представлении это кнопка. При нажатии всплывает поп-ап и я заказываю товар без лишних переходов. Чем быстрее бизнес получит карту пользователя, тем лучше бизнесу ))

2020-11-26 10:39 UTC, mihaqlovm commented on source/catalog.html
> +             <p class="main-goods__description">Показать еще 100500 товаров</p>
Ок, делаю кнопкой, при нажатии на которую на этой же странице подгружаются остальные 100500 товаров. Кстати, это делается на бэке или JS?

2020-11-26 10:39 UTC, mihaqlovm commented on source/catalog.html
> +         <section class="additional-goods page-header__additional-goods">
Да, какая-то дичь получилась ))

2020-11-26 10:40 UTC, mihaqlovm commented on source/catalog.html
> +                            <dt class="visualy-hidden">Объём или вес продукта</dt>
Мотивирует ))

2020-11-26 10:43 UTC, mihaqlovm commented on source/catalog.html
> +    </main>
Не понял. Что не так?
```
<section>
  <h2></h2>
  <p></p>
  <img>
</section>
```

2020-11-26 10:44 UTC, mihaqlovm commented on source/catalog.html
> +    </main>
Ааа, копировал из предыдущей разметки и не туда вставил. Ок, исправлю.

2020-11-26 10:45 UTC, mikhin commented on source/catalog.html
> +                     <div class="main-goods-card">
Типа того. Это же просто например `good-card` или `product-card` — карточка товара.

2020-11-26 10:49 UTC, mikhin commented on source/catalog.html
> +                            <dl>
Пока не знаю. Во-первых классы нужны всегда и везде однозначно, чтоб интерфейс легче считывался из HTML, а вот насчет выделения в БЭМ-блок не знаю)

2020-11-26 10:49 UTC, mikhin commented on source/catalog.html
> +             <p class="main-goods__description">Показать еще 100500 товаров</p>
все что без перезагрузки страницы — на JS

2020-11-26 10:51 UTC, mikhin commented on source/catalog.html
> +    </main>
```
</section>
</main>
```
на одном уровне отступов, а должны быть на разных, т.к. вложенность

2020-11-27 08:17 UTC, closed without merging

2020-11-27 09:17 UTC, mihaqlovm commented on source/catalog.html
> +             <p class="main-goods__description">Показать еще 100500 товаров</p>
Глянул макет. Всё таки я думаю, что это описательная часть. Кнопка ниже. И делать текст интерактивным при наличии кнопки 20 px ниже не вижу резона.