Стилизация страницы формы
htmlacademy-adaptive/1125131-cat-energy-21 pull request #8
Opened 2020-12-06 14:28 UTC by mihaqlovm

2020-12-07 08:23 UTC, mikhin requested changes

2020-12-07 08:23 UTC, mikhin commented on source/catalog.html
> +        <img class="page-header__logo-image logo-image" src="img/logo-mobile-img.png" width="33" height="37" alt="Логотип магазина «Кэт Энэрджи»">
> page-header__logo-image 

Непонятно зачем шапка хочет знать про внутренности логотипа)

2020-12-07 08:23 UTC, mikhin commented on source/catalog.html
> +          <span class="visually-hidden">Открыть меню</span>
👍

2020-12-07 08:23 UTC, mikhin commented on source/catalog.html
> +      <h2 class="visually-hidden">Основные товары</h2>
👍

2020-12-07 08:23 UTC, mikhin commented on source/less/additional-products.less
> +.additional-products__title {
Не хватает отступа

2020-12-07 08:23 UTC, mikhin commented on source/less/button.less
> +  cursor: pointer;
Не, не нужно

2020-12-07 08:23 UTC, mikhin commented on source/less/button.less
> +.button--view-all {
Не считывается функциональный смысл из имени модификатора

2020-12-07 08:23 UTC, mikhin commented on source/less/button.less
> +  width: 280px;
Жестко прибил гвоздями

2020-12-07 08:23 UTC, mikhin commented on source/less/button.less
> +  margin: 0 auto;
Блок не должен хотеть иметь правила внешней геометрии + непонятно почему нет этого правила в базовом классе

2020-12-07 08:23 UTC, mikhin commented on source/less/button.less
>  .button--mobile {
Непонятно почему нужен доп. класс, а не медиа выражение

2020-12-07 08:23 UTC, mikhin commented on source/less/contact.less
> +.contact__backround--white {
Не понятно какая функция у этого класса исходя из имени)

2020-12-07 08:23 UTC, mikhin commented on source/less/contact.less
> +.contact__backround--grey {
Не понятно какая функция у этого класса исходя из имени)

2020-12-07 08:23 UTC, mikhin commented on source/less/copyright.less
> +  padding: 22px 20px;
Какой-то хак, это точно нужно?

2020-12-07 08:23 UTC, mikhin commented on source/less/dist/features-cards.css
> +.features-cards__item {
Отступы нужны)

2020-12-07 08:23 UTC, mikhin commented on source/less/features-cards.less
> +  &:last-child {
👍

2020-12-07 08:23 UTC, mikhin commented on source/less/main-nav.less
> +.main-nav__wrapper-open {
Кажется опечатка по БЭМу в нейминге модификатора

2020-12-07 08:23 UTC, mikhin commented on source/less/dist/page-footer.css
> +.page-footer {
Погоди, кажется папка dist вообще не должна попадать в гит

https://up.htmlacademy.ru/adaptive/21/criteries#b26

2020-12-07 08:23 UTC, mikhin commented on source/less/page__body.less
> +.page__body {
Не, вроде говорили наоборот, делать файлы для блоков, а не для элементов

2020-12-07 08:23 UTC, mikhin commented on source/less/program-request.less
> +.program-request__fieldset-radio {
Вот тут видна проблема нейминга и проектирования абстракций — предметные области (бизнес-область и разработка-интерфейса) жестко связаны. Получается, что исходя из нейминга эту форму нельзя переиспользовать ни для каких других форм, кроме как для формы «Запрос программы».

2020-12-07 08:23 UTC, mikhin commented on source/less/program-request.less
> +.program-request__input-checkbox:checked+.program-request__checkbox {
Давай составной селектор уберем под амперсанд)

2020-12-07 18:56 UTC, mihaqlovm commented on source/less/button.less
> +  cursor: pointer;
На классе ` .button` висят и ссылки, и кнопки. Если уберу `cursor: pointer`, то при наведении на кнопку не появится «рука», сигнализирующая интерактивность.

Объясни, пожалуйста, почему не нужно.

2020-12-07 18:59 UTC, mihaqlovm commented on source/less/button.less
> +.button--view-all {
Сперва я хотел назвать `.button--view-all-product-card`, но решил, что получается слишком длинно. Или нормуль?

2020-12-07 19:01 UTC, mihaqlovm commented on source/less/button.less
> +  width: 280px;
На всех страницах мобильной версии кнопки шириной 280px. На других ширинах экранов будут другие ширины кнопок. Что не так?

2020-12-07 19:04 UTC, mihaqlovm commented on source/less/button.less
> +  margin: 0 auto;
Меня явно подставили ))
Сам не пойму с какой стати тут появился `margin: 0 auto;`.

2020-12-07 19:06 UTC, mihaqlovm commented on source/less/button.less
>  .button--mobile {
А я до медиавыражений ещё не дошёл.
Замечание запомнил, как пройду материал — исправлю.

2020-12-07 19:09 UTC, mihaqlovm commented on source/less/contact.less
> +.contact__backround--white {
Белый фон у блока с контактами. Не?

2020-12-07 19:09 UTC, mihaqlovm commented on source/less/contact.less
> +.contact__backround--grey {
Серый фон у блока с контактами. Что не так?

2020-12-07 19:15 UTC, mihaqlovm commented on source/less/copyright.less
> +  padding: 22px 20px;
Не понял о чём ты. Поэтому опишу почему так:
- без `display: flex` не сработает `justify-content`;
- `justify-content: space-between` нужен, чтобы разнести по краям текст и картинку;
- `align-items: center` центирует картинку по линии с тектом;
- `padding: 22px 20px` не дают контейнеру с текстом и картинкой прилипать к краям.

2020-12-07 19:19 UTC, mihaqlovm commented on source/less/dist/page-footer.css
> +.page-footer {
Довольно странно, что она вообще у меня появилась.

2020-12-07 19:21 UTC, mihaqlovm commented on source/less/page__body.less
> +.page__body {
В рот мне ноги! Не дочистил с прошлого раза.

2020-12-07 19:25 UTC, mihaqlovm commented on source/less/program-request.less
> +.program-request__fieldset-radio {
Ты имеешь ввиду, что нужно отвязаться от названия класса формы в котором лежат эти инпуты и прочее и стилизовать под простой условный fieldset-radio и т. п.?

2020-12-07 19:37 UTC, mikhin commented on source/less/button.less
> +  cursor: pointer;
А зачем переопределять дефолтное поведение браузера в данном случае? В чем профит?

2020-12-07 19:38 UTC, mikhin commented on source/less/button.less
> +.button--view-all {
Не, не нормуль) Непонятно почему кнопка хочет знать про какой-то «посмотреть все» или про какие-то «карточки» =)

2020-12-07 19:40 UTC, mikhin commented on source/less/button.less
> +  width: 280px;
Непонятная функция этого класса. Я идею с шириной кнопки и другими ширинами экрана не понял, если честно. Плюс непонятно почему нейминг про мобильность и тут же определяется размер шрифта, текст-трансформ и все такое

2020-12-07 19:40 UTC, mikhin commented on source/less/contact.less
> +.contact__backround--white {
Это не функция, а визуальная составляющая. Мы не должны хотеть именовать исходя из визуального, мы должны хотеть именовать исходя из функционального)

2020-12-07 19:41 UTC, mikhin commented on source/less/copyright.less
> +  padding: 22px 20px;
Не, я конкретно про паддинг, но вроде ОК, я че-т прогнал

2020-12-07 19:42 UTC, mikhin commented on source/less/program-request.less
> +.program-request__fieldset-radio {
В эту сторону подумать, да

2020-12-07 19:42 UTC, mikhin commented
@mihaqlovm, еще проверка упала

2020-12-07 19:53 UTC, mihaqlovm commented
> @mihaqlovm, еще проверка упала

Починил.

2020-12-08 16:27 UTC, mihaqlovm commented on source/less/button.less
> +  cursor: pointer;
Не знаю. Мне казалось так нагляднее. Хотя в реальности там же ховер будет. Убрал.

2020-12-08 16:28 UTC, mihaqlovm commented on source/less/button.less
> +.button--view-all {
И как быть? Положить кнопку в контейнер `view-all-product-card`?

2020-12-08 16:31 UTC, mihaqlovm commented on source/less/button.less
> +  width: 280px;
Ширину задал в 100%. Ну, а где мне указывать размер шрифта?! ((

2020-12-08 16:33 UTC, mihaqlovm commented on source/less/contact.less
> +.contact__backround--white {
Ок, добавил независимый блок `backround` и модифицирую его согласно цветовой схеме. Норм?

2020-12-08 16:35 UTC, mihaqlovm commented on source/less/program-request.less
> +.program-request__fieldset-radio {
`<label class="label label-radio" for="weight-loss">Похудение</label>`
`<input class="visually-hidden input-radio" type="radio" name="result" value="weight-loss" id="weight-loss" checked>`

Оно?

2020-12-08 17:33 UTC, mikhin commented on source/less/program-request.less
> +.program-request__fieldset-radio {
ну примерно да, но теперь к бэм-блокам этой абстракции тоже есть вопросы)

2020-12-08 17:36 UTC, mikhin commented on source/less/contact.less
> +.contact__backround--white {
не, не норм. в целом у нас не должно быть «визуальных» абстракций. Потому что, например, белый фон, он на самом деле не белый, а «базовый», т.е. в этом его функциональная суть. Кнопка, к примеру, не «зеленая», а «кнопка первичного действия». Надо думать в сторону функций, и никогда в сторону визуального.

2020-12-08 17:36 UTC, mikhin commented
@mihaqlovm, вижу что проверка упала опять

2020-12-08 17:37 UTC, mikhin commented on source/less/button.less
> +  width: 280px;
В той функциональной абстракции, которая хочет отвечать за размер шрифта)

2020-12-08 17:37 UTC, mikhin commented on source/less/button.less
> +.button--view-all {
Эм, не знаю 🤷‍♂️

2020-12-08 18:12 UTC, mihaqlovm commented on source/less/button.less
> +.button--view-all {
Сделаю так, а там будь что будет:
1. Просто `button`
2. И `button` с модификатором `special`

То есть будет одна стандартная кнопка, которую я буду изменять медиазапросами под нужную ширину экрана и одна спец. кнопка.

2020-12-08 18:19 UTC, mihaqlovm commented on source/less/contact.less
> +.contact__backround--white {
То есть так:
`.background--special {
background-color: @grey-basic; }`

`.background--basic { background-color: @white; }`

?

2020-12-08 18:28 UTC, mihaqlovm commented on source/less/program-request.less
> +.program-request__fieldset-radio {
Ну, это поправимо:
`fieldset-radio`
`fieldset-radio__label`
`fieldset-radio__input`

2020-12-08 18:57 UTC, mikhin approved these changes

2020-12-08 18:57 UTC, mikhin commented on source/less/program-request.less
> +.fieldset-radio__label {
Этот БЭМ-блок должен быть в своем отдельном файле

2020-12-08 18:57 UTC, mikhin commented on source/less/program-request.less
> +  &:checked + .program-request__checkbox {
Непонятно почему для радио абстракция отделена, а для чекбокса нет)

2020-12-08 18:57 UTC, mikhin commented on source/less/button.less
> +.button--special {
Все равно по коду непонятно что значит, придется лезть в браузер и изучать мировозрение автора)

2020-12-08 18:57 UTC, mikhin commented on source/less/background.less
> +.background--special {
Не, такая абстракция не должна хотеть существовать) Непонятно в чем особенность такого блока, в чем его функция, и как его применять)

2020-12-08 18:57 UTC, mikhin commented on source/less/background.less
> +.background--special {
Это получается Атомарный CSS, а у нас другая методология — у нас божественный БЭМ 

https://habr.com/ru/post/432586/

2020-12-08 18:57 UTC, mikhin commented on source/less/additional-card.less
> +  font-family: "Arial", sans-serif;
А нам еще запасные шрифты не нужно указывать? Не знаю, рили спрашиваю

2020-12-08 18:57 UTC, mikhin commented on source/form.html
> +                <fieldset class="fieldset fieldset-radio program-request__fieldset">
`fieldset` и `fieldset-radio` — по коду непонятно как они работают, может ли допустим один быть без другого.

2020-12-08 18:57 UTC, mikhin commented on source/catalog.html
> +      <a href="#" class="page-header__link">
По коду непонятно что такое «ссылка в хедере»

2020-12-08 18:57 UTC, merged

2020-12-09 18:35 UTC, mihaqlovm commented on source/less/button.less
> +.button--special {
Сдаюсь. Как бы ты назвал?

2020-12-09 18:36 UTC, mihaqlovm commented on source/less/background.less
> +.background--special {
А к чему тогда привязаться?!
Не думал, что нэйминг станет таким сложным и будет сжирать так много времени.

2020-12-09 18:40 UTC, mihaqlovm commented on source/less/additional-card.less
> +  font-family: "Arial", sans-serif;
Какие такие запасные? На Виндятине Arial считается безопасным шрифтом, потому что установлен в систему по умолчанию. Если не будет Arial'а, то подгрузится любой другой системный шрифт без засечек — это мы говорим браузеру посредством `sans-serif`.

2020-12-09 18:42 UTC, mihaqlovm commented on source/form.html
> +                <fieldset class="fieldset fieldset-radio program-request__fieldset">
Как можно понять, прочитав название классов у одного тега, что один класс без другого может или не может работать? О_О
Покажи пример, пожалуйста.

2020-12-09 18:42 UTC, mikhin commented on source/less/additional-card.less
> +  font-family: "Arial", sans-serif;
Окей)

2020-12-09 18:43 UTC, mikhin commented on source/less/background.less
> +.background--special {
> Не думал, что нэйминг станет таким сложным и будет сжирать так много времени

Никто не ожидает, да. Именовать в JS правильно будет еще сложнее =)

2020-12-09 18:43 UTC, mihaqlovm commented on source/catalog.html
> +      <a href="#" class="page-header__link">
Почему?! ((
Ну, что тут не так; что именно не понятно? Мне понятно — ссылка в шапке страницы, норм же ж.

2020-12-09 18:44 UTC, mikhin commented on source/catalog.html
> +      <a href="#" class="page-header__link">
А что за ссылка? На что ссылается и какая у нее функция?

2020-12-09 18:45 UTC, mikhin commented on source/form.html
> +                <fieldset class="fieldset fieldset-radio program-request__fieldset">
Не, я к тому что ты ща бахнул на одну ноду два разных БЭМ-блока + БЭМ-элемент. По коду непонятно зачем такое нужно и что за этим кроется)

2020-12-09 18:47 UTC, mikhin commented on source/less/background.less
> +.background--special {
Привязаться надо к функции элемента. Белый или красный или серо-бур-малиновый — цвета не спроста на каждом своем месте. Надо понять систему и отразить ее в CSS, причем отразить выразительно, чтобы программисту с любой картиной мира было понятно о чем речь)

2020-12-09 18:48 UTC, mihaqlovm commented on source/catalog.html
> +      <a href="#" class="page-header__link">
При клике на эту ссылку, при условии, что мы находимся на отличной от index.html странице, мы попадём на эту самую страницу — на index.html Если же мы на ней, то ссылка работать не будет.

Итого: `page-header__link-to-main`? Как-то странно, как по мне.

2020-12-09 18:49 UTC, mihaqlovm commented on source/form.html
> +                <fieldset class="fieldset fieldset-radio program-request__fieldset">
А, ну я завалю `fieldset `.
Останется только: `<fieldset class="fieldset-radio program-request__fieldset">`.
И по остальным подобным случаям поступлю аналогично.

2020-12-09 18:50 UTC, mikhin commented on source/form.html
> +                <fieldset class="fieldset fieldset-radio program-request__fieldset">
Да, так будет почище и поочевиднее

2020-12-09 18:53 UTC, mikhin commented on source/catalog.html
> +      <a href="#" class="page-header__link">
Ты вот в какую сторону подумай — сейчас `page-header` чрезмерно жирный блок, который лезет щупальцами туда, куда лезть не должен хотеть. Он отвечает сейчас слишком за многое: и за раскладку элементов внутри себя, и за ссылки какие-то, и за логотип.

Я вот тут чутка у Даши описал тоже самое, практически, глянь  — https://github.com/htmlacademy-adaptive/1579099-sedona-21/pull/8#discussion_r538612775