Стилизовал страницу каталога
htmlacademy-adaptive/1125131-cat-energy-21 pull request #9
Opened 2020-12-19 16:57 UTC by mihaqlovm

2020-12-21 07:33 UTC, undgrnd requested changes

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +      <a href="/">
Нужно добавить класс

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +          <source srcset="img/logo-mobile.png" media="(max-width: 767px)">
Непонятно зачем две мобильные картинки

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +          <source srcset="img/logo-desktop.png" media="(min-width: 1440px)">
Непонятно почему использованы и min-width и max-width

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +            <a class="main-nav__link main-nav__link--active">Каталог продукции</a>
Ссылка не может быть без href

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +          <li class="catalog__item catalog__main-item">
А зачем нужна два элемента?

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +        <ul class="catalog__list catalog__main-list">
А зачем нужна два элемента?

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +              <div class="product-card__container">
Непонятно по коду по имени класса что это за контейнер, если выше был контейнер для изображения

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +            <div class="product-card product-card--special">
Я думаю что это не карточка товара, а какой-то другой БЭМ-блок

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +                <div class="catalog__svg"></div>
Непонятно что это и зачем)

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +      <div class="container__desktop">
Очень плохое имя класса и непонятно зачем нужен этот элемент

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +            <li class="catalog__item">
БЭМ-блок `catalog` зашел слишком далеко, он стал слишком жирным и отвечает уже за слишком многое. По идее, в иделае, он должен только отвечает за минимальную раскладку блоков на странице и хотеть лезть во внутренности своих детей не должен.

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +                  <dl class="additional-card__list">
Мегалойс 👍

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +            <section class="gift-banner">
Не тянет на section

2020-12-21 07:33 UTC, undgrnd commented on source/catalog.html
> +    <div class="page-footer__container container">
`page-footer__container` — для начала, во всех таких случая, можно смело заменять на `page-footer__content`, станет гораздо понятнее)

2020-12-21 07:33 UTC, undgrnd commented on source/form.html
> +                <fieldset class="fieldset fieldset-checkbox program-request__fieldset">
Непонятно зачем нужно два БЭМ-блока на одном узле

2020-12-21 07:33 UTC, undgrnd commented on source/form.html
> +                      <label class="label program-request__label fieldset-checkbox__label" for="sugar-substitute">Сахарозаменитель</label>
Многовато БЭМ-элементов на одном узле, получается какая-то каша. Расскажешь что тут к чему?)

2020-12-21 07:33 UTC, undgrnd commented on source/index.html
> +      <section class="promo-banner promo-banner__background page-main__promo-banner">
`promo-banner__background` плохое имя класса

2020-12-21 07:33 UTC, undgrnd commented on source/less/catalog.less
> +    margin-bottom: 190px;
А это никакой не паддиг точно?

2020-12-21 07:33 UTC, undgrnd commented on source/less/catalog.less
> +  @media (min-width: @tablet-width) {
Кстати, это медиа выражение нужно запихнуть внутрь вышестоящего определения last-child

2020-12-21 07:33 UTC, undgrnd commented on source/less/catalog.less
> +  @media (min-width: @tablet-width) {
И т.к. last-child это по сути отдельный селектор и ты определяешь медиа-выражения внутри отдельных селекторов, как я вижу, то все медиа-выражения для last-child нужно определять внутри него)

2020-12-21 07:33 UTC, undgrnd commented on source/less/catalog.less
> +  overflow: hidden;
А это зачем?

2020-12-21 07:33 UTC, undgrnd commented on source/less/catalog.less
> +  @media (min-width: @tablet-width) {
Писал выше уже, это медиа выражение нужно убрать внутрь соответствующего селектора

2020-12-21 07:33 UTC, undgrnd commented on source/less/catalog.less
> +.catalog__svg {
Плохое имя класса

2020-12-21 07:33 UTC, undgrnd commented on source/less/catalog.less
> +    &:nth-child(1n+5) {
О, а это для чего?

2020-12-21 07:33 UTC, undgrnd commented on source/less/container.less
> +.container__tablet {
Эти имена классов лучше переработать)

2020-12-21 07:33 UTC, undgrnd commented on source/less/fieldset-checkbox.less
> +.fieldset-checkbox__label {
А можем избавиться от привязки к филдсету в нейминге и сделать просто отдельным БЭМ-блоком чекбокса?

2020-12-21 07:33 UTC, undgrnd commented on source/less/fieldset-checkbox.less
> +.fieldset-checkbox__label {
Тоже самое касается и радио-кнопки

2020-12-21 07:33 UTC, undgrnd commented on source/less/fieldset-radio.less
> +  cursor: pointer;
Это для чего?)

2020-12-21 07:33 UTC, undgrnd commented on source/less/wrapper.less
> +.wrapper {
Непонятно что за блок, кажется у нас уже есть container, а этот лучше удалить)

2020-12-25 06:27 UTC, mikhin commented
Нужно добавить центрирование контента для всех страниц

<img width="1257" alt="Снимок экрана 2020-12-25 в 09 26 31" src="https://user-images.githubusercontent.com/38258318/103122907-53808300-4693-11eb-9b32-b19288dfb38b.png">

2020-12-25 06:29 UTC, mikhin commented
Нужно чтоб на странице каталога, на ширине до 1440 был планшетный вид, как в макете. Сейчас выглядит по-другому.
<img width="1279" alt="Снимок экрана 2020-12-25 в 09 27 52" src="https://user-images.githubusercontent.com/38258318/103122975-99d5e200-4693-11eb-85d4-89189c753de7.png">

<img width="1280" alt="Снимок экрана 2020-12-25 в 09 29 04" src="https://user-images.githubusercontent.com/38258318/103122990-a6f2d100-4693-11eb-8a39-6cac8817005e.png">

2020-12-25 06:35 UTC, mikhin commented
@mihaqlovm, большая работа проделана! Получается достойно! 👍

2020-12-25 06:35 UTC, mikhin approved these changes

2020-12-25 06:35 UTC, mikhin commented on source/catalog.html
> +            <div class="main-card">
«главная карточка» звучит непонятно, если не смотреть в макет и в браузер)

2020-12-25 06:35 UTC, mikhin commented on source/catalog.html
> +              <div class="main-card__canvas">
`main-card__image-canvas`

2020-12-25 06:35 UTC, mikhin commented on source/less/additional-goods.less
> +  display: block;
Списки вроде и так блочные по умолчанию

2020-12-25 06:35 UTC, mikhin commented on source/less/additional-goods.less
> +  align-items: start;
Непонятно зачем нужно, если тут нет гридов и флексов

2020-12-25 06:35 UTC, mikhin commented on source/less/additional-goods.less
> +  @media (min-width: @tablet-width) {
Нужно убрать медиа-выражение внутрь селектора, так будет удобнее

2020-12-25 06:35 UTC, mikhin commented on source/less/products-card.less
> +.products-card {
Не понял по имени класса что это за блок и полез смотреть в браузер. Это скорее `more-products-cards`)

2020-12-25 06:35 UTC, mikhin commented on source/less/products-card.less
> +      content: url("../img/plus-tablet.svg");
А этот не один и тот же плюс, просто в разных размерах? Может получится обойтись одной картинкой?

2020-12-25 06:35 UTC, merged

2020-12-25 18:26 UTC, mihaqlovm commented on source/catalog.html
> +            <div class="main-card">
Я побоялся назвать `main-product-card`. Или норм?

2020-12-25 20:49 UTC, mihaqlovm commented on source/catalog.html
> +            <div class="main-card">
Урок выучен. Но пока что оставим как есть.